[workspace]
members = ["evm", "field", "maybe_rayon", "plonky2", "starky", "util"]
resolver = "2"

[profile.release]
opt-level = 3
incremental = true
#lto = "fat"
#codegen-units = 1

[profile.bench]
opt-level = 3

[patch."https://github.com/mir-protocol/plonky2"]
plonky2 = { path = "plonky2" }